### ISSUE TITLE
Incompatible tree-sitter

### ISSUE THREAD

**Issue by dwarfmaster** [nvim-neorg/nixpkgs-neorg-overlay#6]
The `neorg` and `tree-sitter-norg` used in the overlay are incompatible, resulting in `invalid node type` errors. This is probably due to the refactors due to 1.0, but it can temporarily be fixed by using the `dev` branch of `tree-sitter-norg`.

**Comment by max397574** [comment]
This can and should be fixed with `:Neorg sync-parsers`

**Comment by dwarfmaster** [comment]
I am using nix to manage the treesitter grammars, so I'd like to avoid that option (especially since it fails, probably because the treesitter directory is readonly since it is in the nix store).

**Comment by bandithedoge** [comment]
> This can and should be fixed with `:Neorg sync-parsers`

The entire point of this overlay is to install parsers in a declarative and reproducible way. Doing it manually defeats the purpose of using Nix for your configuration.

**Comment by bandithedoge** [comment]
I modified the `tree-sitter-norg` input to use the `dev` branch (which makes sense anyway given the bleeding edge nature of this overlay), although it required cherry-picking `flake.nix` from `main` to work.
