### ISSUE TITLE
`lua-utils` not found

### ISSUE THREAD

**Issue by florentc** [nvim-neorg/nixpkgs-neorg-overlay#8]
When using the overlay to setup a neovim configuration in home-manager with Neorg, the plugin (even with only the `core.defaults` module loaded) doesn't work and prints a warning about `lua-utils` being not found. No neorg module is loaded, and there is no treesitter highlighting.

The same issue occurs with the `neorg` package on nixpkgs (I used this overlay hoping not to encounter the same issue).

This seems related to the switch to neorg version 8. Maybe there are new dependencies to declare for the neorg package on nixpkgs and in this overlay.

I tried to add neorg's dependencies (to my knowledge `lua-utils` `nvim-nio` `nui-nvim` `plenary-nvim` as plugins explicitly in the `plugins` field of my neovim home-manager config. I imported `lua-utils` manually with `buildVimPlugin` because it is not provided in nixpkgs or this overlay. I end up with partially working neorg (mainly treesitter highlighting) but most modules fail to load.

**Comment by thomaslaich** [comment]
Same issue. the overlay no longer works for me since neorg 8.0.0.

**Comment by mandlm** [comment]
Same here

**Comment by bandithedoge** [comment]
I added dependencies for 8.0.0 in https://github.com/nvim-neorg/nixpkgs-neorg-overlay/commit/b73ee530eb96d4d363dd6409f0d93ace4549c5b8. Please let me know if this works for you.

**Comment by thomaslaich** [comment]
Works like a charm! thanks

**Comment by florentc** [comment]
Awesome, thanks!
